Feature/create package cms 2350
PrimarySite/django-transitions pull request #1
Opened 2018-11-12 16:19 UTC by cleder

2018-11-13 14:48 UTC, ecilveks approved these changes

2018-11-14 10:11 UTC, amusikal requested changes
A couple of typos, but otherwise looks good :+1:

2018-11-14 10:11 UTC, amusikal commented on docs/source/faq.rst
> +The code from this package was lifted from the tread `django and transitions`_
[typo] `tread`?

2018-11-14 10:11 UTC, amusikal commented on docs/source/faq.rst
> +What is the history of django and pytransition integration?
[typo] ~pytransition~ pytransition**s**

2018-11-14 10:56 UTC, amusikal approved these changes

2018-11-14 11:58 UTC, merged